In [4]:
# let import libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

# lets load the data
air_conditioners = pd.read_csv(r"C:\Users\jki\Downloads\Aamzon Datasets\Air Conditioners.csv")

air_conditioners.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790"

In [5]:
# lets inspect the statsistcial summry
air_conditioners.describe()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
count,720,720,720,720,720,433,433,457,500
unique,708,1,1,635,720,31,187,295,296
top,Samsung 1.5 Ton 3 Star Wind-Free Technology In...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.0,1,"₹39,990","₹59,990"
freq,3,720,720,6,1,56,45,11,15

In [6]:
# let check for missing values
missing_values = air_conditioners.isna().sum()
print(missing_values)

name                0
main_category       0
sub_category        0
image               0
link                0
ratings           287
no_of_ratings     287
discount_price    263
actual_price      220
dtype: int64

In [8]:
# lets drop missing values
air_conditioners.dropna(subset=['ratings'],inplace =True )
air_conditioners.dropna(subset=['no_of_ratings'],inplace =True )  
air_conditioners.dropna(subset=['discount_price'],inplace =True )  
air_conditioners.dropna(subset=['actual_price'],inplace =True )  

# let check for missing values
missing_values = air_conditioners.isna().sum()
print(missing_values)

name              0
main_category     0
sub_category      0
image             0
link              0
ratings           0
no_of_ratings     0
discount_price    0
actual_price      0
dtype: int64