In [3]:
# Let import librries

import pandas as pd
import numpy as np

# load the data
espn_cricket_df = pd.read_csv(r"C:\Users\jki\Downloads\ESP Cricket Data.csv")
espn_cricket_df

,Player,Span,Mat,Inns,NO,Runs,HS,*Ave*,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,*99.94*,9800+,58.6,29,13,7,626+,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,*62.15*,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,*61.87*,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,*60.97*,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,*60.83*,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,*48.26*,8662+,49.16,15,33,4,525+,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,*48.25*,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,*48.22*,3118+,44.77,7,6,1,119+,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,*48.21*,3217+,60.02,6,13,4,241+,5+
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,*48.00*,2110+,25.59,1,10,2,53+,0

Note: you may need to restart the kernel to use updated packages.

ERROR: unknown command "to"