In [1]:

# Load in some packages
import calendar
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# load dataset
bigmart_sales_df = pd.read_csv(r"C:\Users\jki\Downloads\2  BigMart\Source Files\Cleaned Data\Big Mart Sales.csv" )  
bigmart_sales_df

,ProductID,Weight,FatContent,ProductVisibility,ProductType,MRP,Quantity,Sales,OutletID,Date,OutletSize,LocationType,OutletType
0,FDW58,21.0,Low Fat,0,Snack Foods,108,10000.0,"1,078,622.00",OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.0,reg,0,Dairy,87,10000.0,"873,198.00",OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,15.0,Low Fat,0,Others,242,10000.0,"2,417,538.00",OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.0,Low Fat,0,Snack Foods,155,10000.0,"1,550,340.00",OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0,Dairy,234,10000.0,"2,342,300.00",OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,11.0,Regular,0,Snack Foods,141,NaN,"1,413,154.00",OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,8.0,Regular,0,Starchy Foods,169,NaN,"1,691,448.00",OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.0,Low Fat,0,Health and Hygiene,119,NaN,"1,187,440.00",OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.0,Regular,0,Canned,215,NaN,"2,146,218.00",OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,10.0,Regular,0,Canned,80,NaN,"797,960.00",OUT045,2002,NaN,Tier 2,Supermarket Type1