In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\jki\Desktop\Preactse Data sets\Big Mart Sales.csv")
df

,ProductID,Weight,FatContent,ProductVisibility,ProductType,MRP,Sales,Budgeted Sales,OutletID,Date,OutletSize,LocationType,OutletType
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,"107,862.20","92,761.49",OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,"87,319.80","75,095.03",OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,"241,753.80","207,908.27",OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,"155,034.00","133,329.24",OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,"234,230.00","201,437.80",OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,"141,315.40","121,531.24",OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,"169,144.80","145,464.53",OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,"118,744.00","102,119.84",OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,"214,621.80","184,574.75",OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,"79,796.00","68,624.56",OUT045,2002,NaN,Tier 2,Supermarket Type1

In [6]:
df = df.drop_duplicates()
df

,ProductID,Weight,FatContent,ProductVisibility,ProductType,MRP,Sales,Budgeted Sales,OutletID,Date,OutletSize,LocationType,OutletType
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,"107,862.20","92,761.49",OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,"87,319.80","75,095.03",OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,"241,753.80","207,908.27",OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,"155,034.00","133,329.24",OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,"234,230.00","201,437.80",OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,"141,315.40","121,531.24",OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,"169,144.80","145,464.53",OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,"118,744.00","102,119.84",OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,"214,621.80","184,574.75",OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,"79,796.00","68,624.56",OUT045,2002,NaN,Tier 2,Supermarket Type1

In [7]:
df["OutletSize"] = df["OutletSize"].str.replace('Medium','M')

In [8]:
df

,ProductID,Weight,FatContent,ProductVisibility,ProductType,MRP,Sales,Budgeted Sales,OutletID,Date,OutletSize,LocationType,OutletType
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,"107,862.20","92,761.49",OUT049,1999,M,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,"87,319.80","75,095.03",OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,"241,753.80","207,908.27",OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,"155,034.00","133,329.24",OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,"234,230.00","201,437.80",OUT027,1985,M,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,"141,315.40","121,531.24",OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,"169,144.80","145,464.53",OUT018,2009,M,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,"118,744.00","102,119.84",OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,"214,621.80","184,574.75",OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,"79,796.00","68,624.56",OUT045,2002,NaN,Tier 2,Supermarket Type1

In [9]:
df["OutletSize"] = df["OutletSize"].str.replace('Small','S')

In [10]:
df

,ProductID,Weight,FatContent,ProductVisibility,ProductType,MRP,Sales,Budgeted Sales,OutletID,Date,OutletSize,LocationType,OutletType
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,"107,862.20","92,761.49",OUT049,1999,M,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,"87,319.80","75,095.03",OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,"241,753.80","207,908.27",OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,"155,034.00","133,329.24",OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,"234,230.00","201,437.80",OUT027,1985,M,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,"141,315.40","121,531.24",OUT046,1997,S,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,"169,144.80","145,464.53",OUT018,2009,M,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,"118,744.00","102,119.84",OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,"214,621.80","184,574.75",OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,"79,796.00","68,624.56",OUT045,2002,NaN,Tier 2,Supermarket Type1

In [ ]:
df["OutletSize"] = df["OutletSize"].str.replace('NaN','')