Internet Sales Adventure Wokrs Dataset

Data Exploration & Cleaning

The first part of any data analysis or predictive modeling task is an initial exploration of the data. Even if you collected the data yourself and you already have a list of questions in mind that you want to answer, it is important to explore the data before doing any serious analysis, since oddities in the data can cause bugs and muddle your results. Before exploring deeper questions, you have to answer many simpler ones about the form and quality of data. That said, it is important to go into your initial data exploration with a big picture question in mind since the goal of your analysis should inform how you prepare the data.

In [1]:

# Load in some packages
import calendar
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

# lets load the dataset
internet_sales_df  = pd.read_csv(r"C:\Users\jki\Downloads\1 Adventure Wokrs\clean data\Internet Sales.csv")
internet_sales_df

,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,CustomerKey,PromotionKey,CurrencyKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,...,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight,CarrierTrackingNumber,CustomerPONumber,OrderDate,DueDate,ShipDate
0,310,20101229,20110110,20110105,21768,1,19,6,SO43697,1,...,2171,2171,3578,286,89,NaN,NaN,00:00.0,00:00.0,00:00.0
1,346,20101229,20110110,20110105,28389,1,39,7,SO43698,1,...,1912,1912,3400,272,85,NaN,NaN,00:00.0,00:00.0,00:00.0
2,346,20101229,20110110,20110105,25863,1,100,1,SO43699,1,...,1912,1912,3400,272,85,NaN,NaN,00:00.0,00:00.0,00:00.0
3,336,20101229,20110110,20110105,14501,1,100,4,SO43700,1,...,413,413,699,56,17,NaN,NaN,00:00.0,00:00.0,00:00.0
4,346,20101229,20110110,20110105,11003,1,6,9,SO43701,1,...,1912,1912,3400,272,85,NaN,NaN,00:00.0,00:00.0,00:00.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,311,20110628,20110710,20110705,18332,1,6,9,SO45020,1,...,2171,2171,3578,286,89,NaN,NaN,00:00.0,00:00.0,00:00.0
996,348,20110628,20110710,20110705,11358,1,6,9,SO45021,1,...,1898,1898,3375,270,84,NaN,NaN,00:00.0,00:00.0,00:00.0
997,350,20110628,20110710,20110705,11447,1,6,9,SO45022,1,...,1898,1898,3375,270,84,NaN,NaN,00:00.0,00:00.0,00:00.0
998,310,20110628,20110710,20110705,13807,1,29,8,SO45023,1,...,2171,2171,3578,286,89,NaN,NaN,00:00.0,00:00.0,00:00.0
999,344,20110629,20110711,20110706,29475,1,29,8,SO45024,1,...,1912,1912,3400,272,85,NaN,NaN,00:00.0,00:00.0,00:00.0